pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: ./build.ps1
  displayName: 'Run Cake build script'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: website'
  inputs:
    PathtoPublish: output
    ArtifactName: website
