trigger:
- master

pr:
- none

pool:
  vmImage: 'vs2017-win2016'

steps:
-script: |
  dotnet tool install --tool-path . Wyam.Tool

- script: |
  wyam
  displayName: 'Build website'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: website'
  inputs:
    PathtoPublish: output
    ArtifactName: website
