trigger:
- master

pr:
- none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install Wyam.Tool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Wyam.Tool'

- task: BatchScript@1
  displayName: 'Build website'
  inputs:
    filename: wyam

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: website'
  inputs:
    PathtoPublish: output
    ArtifactName: website
